/** Подписи экранов в одном месте. */
export const texts = {
    app: {
        title: "Чат",
        back: "Назад",
        cancel: "Отмена",
        logout: "Выйти",
        chats: "Чаты",
        menu: "Меню",
        lightTheme: "Светлая тема",
        darkTheme: "Тёмная тема",
        resizeSidebar: "Потяните край списка, чтобы свернуть или развернуть",
    },
    auth: {
        submit: "Войти",
        pending: "Проверяем инстанс…",
        showToken: "Показать токен",
        hideToken: "Скрыть токен",
        hint: "Выберите тот же мессенджер, что и при создании инстанса в личном кабинете.",
        apiUrl: "apiUrl",
        idInstance: "idInstance",
        token: "apiTokenInstance",
        messenger: "Мессенджер",
        whatsapp: "WhatsApp",
        telegram: "Telegram",
        failed: "Не удалось войти",
    },
    chat: {
        newChat: "Новый чат",
        emptyList: "Чатов пока нет. Создайте диалог по номеру телефона.",
        emptyThread: "Напишите первое сообщение",
        noMessages: "Нет сообщений",
        placeholder: "Выберите чат или создайте новый",
        personal: "Личный чат",
        message: "Сообщение",
        send: "Отправить",
        phone: "Телефон",
        phoneHint: (messenger: string) => `Номер получателя в ${messenger}. Например, 79991234567.`,
        phoneInvalid: "Введите номер в международном формате, например 79991234567",
        create: "Создать чат",
        checking: "Проверяем…",
        createFailed: "Не удалось создать чат",
        retry: "Не отправлено. Повторить",
        tooLong: (limit: number) => `Сообщение длиннее ${limit} символов`,
        sendFailed: "Не удалось отправить сообщение",
        dialog: "Диалог",
        restarting:
            "Инстанс перезапускается, чтобы включить получение сообщений по HTTP API. Это может занять до 5 минут.",
        settingsFailed: "Не удалось настроить получение сообщений",
        status: {
            connecting: "Подключение",
            ready: "Сообщения приходят",
            restarting: "Инстанс перезапускается",
            error: "Нет связи с API",
        },
    },
} as const;
